### PR TITLE
Register Server workers list sorting changed, PEP8

### PR DESCRIPTION
**Pull request by GrivIN**
Most value changes in utils.server and utils.registry.

* Added tasks property to class:Server - return number of connected clients (maybe should be a number of subprocesses/threads?)
* Workers provide information about connected clients to Register Server (func: [UDP, TCP]RegistryClient.register())
* List of available workers provided by Register Server (func: cmd_query) - clients is sorted by number of connected clients to worker.
* Some PEP8 fixes in code - spaces and newlines
* Fix in Server docstring about param:registrar - object is needed here not a class

### CODE REVIEW

**Comment by tomerfiliba** [comment]
Hi @GrivIN - can you separate the whitespace/PEP8 changes from the logical ones, i.e., into two commits? I'm having hard time going over the changes. Also, please note that the travis tests are broken

**Comment by GrivIN** [comment]
true, i fixed travis cmd_register to let tests pass, ok, i will separate commits

**Comment by GrivIN** [comment]
Hi @tomerfiliba - now should be ok,

**Comment by tomerfiliba** [comment]
hey @GrivIN, can you fix the travis build and i'll merge it in?

**Pull request closed without merging**
