### PR TITLE
numed workers, logging exceptions fix

### PR DESCRIPTION
**Pull request by xBeAsTx**
small fix

### CODE REVIEW

**Comment by coldfix** [comment]
@xBeAsTx This seems mostly fine. One question: why are you removing the exception text from the warning (last chunk in the diff)

**Comment by xBeAsTx** [comment]
@coldfix logger.exception do all work inside.
https://docs.python.org/2/library/logging.html#logging.Logger.exception
```Exception info is always added to the logging message. This method should only be called from an exception handler.```

**Comment by coldfix** [comment]
Oh thanks. I missed you changed to `logging.exception`.

Can you rebase against current master and resolve conflicts?

Many thanks, Thomas

**Comment by xBeAsTx** [comment]
@coldfix Done. Is it you tomerfiliba?

**Comment by tomerfiliba** [comment]
@xBeAsTx - coldfix is a maintainer now

**Comment by coldfix** [comment]
No, I stepped in as maintainer until tomerfiliba has more time and wants to take back control.

**Pull request merged**
