### PR TITLE
Asynchronous Windows named pipes

### PR DESCRIPTION
**Pull request by pyscripter**
Non blocking poll.   1000 times faster than current implementation.  40% faster than sockets for local connections.

### CODE REVIEW

**Comment by pyscripter** [comment]
Tested all with Python 2.7, 3,6, 3.7.   All work fine.  I am done with this PR.

**Comment by coldfix** [comment]
Hey, awesome, thanks!

I will merge without the last commit (while it might be slightly better in terms of import times, I don't think it's very idiomatic and worth the benefit).

**Comment by pyscripter** [comment]
I am fine with that.  Just for the record the main benefit of removing the safe-imports is not to improve import times but to avoid importing modules that are not used altogether.   For example a broken pywin32 installation could make rpyc unusable.

**Comment by coldfix** [comment]
I see. In the long-term, I think this should be solved by better separation of imports (i.e. putting this class and its import dependencies in a separate module that is imported by the user directly), or lazy imports (if python ever supports it natively, or maybe by patching the `safe_import` function to perform lazy importing.

**Comment by pyscripter** [comment]
` by patching the safe_import function to perform lazy importing.`
I was thinking about that...

**Pull request merged**
