### PR TITLE
Ensuring that we get a server we can connect to from the list.

### PR DESCRIPTION
**Pull request by adubey14**
Registry client returns first registry server it could connect to (instead of the first element of the list of all registered servers).

### CODE REVIEW

**Comment by coldfix** [comment]
Hi,

thanks for your interest. Can you clean up a few things before merge:

- most importantly: qualify the except clause with the appropriate exception type
- remove NOP `else: pass`
- join `ret = ...; return ret`  into a single line `return ...`
- use `for i, (host, port) in enumerate(addrs)` instead of manually counting `addrl`

**Comment by coldfix** [comment]
> what exception should we use (what will connect_stream throw)?

The one that you were getting and trying to avoid due to a server being down, i.e. the purpose of this PR.

Why did you push a random new version?

Nevermind, I'll clean it up.

**Comment by adubey14** [comment]
Sorry, I needed a new version locally to force and update over my existing installation. It was not supposed to be included in the pull request. I will clean up and send you an updated patch directly.

Sent from my iPad

On Jul 28, 2017, at 6:18 AM, Thomas G. <notifications@github.com<mailto:notifications@github.com>> wrote:


what exception should we use (what will connect_stream throw)?

The one that you were getting and trying to avoid due to a server being down, i.e. the purpose of this PR.

Why did you push a random new version?

Nevermind, I'll clean it up.

**Comment by coldfix** [comment]
It's okay. Don't bother I already merged a cleaned up version.

**Comment by adubey14** [comment]
Thank you. Sorry for the inconvenience. I will pull in your changes directly.

Sent from my iPad

On Jul 28, 2017, at 6:47 AM, Thomas G. <notifications@github.com<mailto:notifications@github.com>> wrote:


It's okay. Don't bother I already merged a cleaned up version.

**Pull request closed without merging**
